version: "3.9"

services:
  db:
    image: postgres:15
    container_name: mf_guru_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mf_guru
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: mf_guru_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/mf_guru
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:
